#pragma once

enum class SAMPLER_STATE {
    POINT,
    LINEAR,
    ANISOTROPIC,

    MAX
};
enum class DEPTH_STATE {
    ENABLE_AND_WRITE,
    DISABLE_AND_WRITE,
    ENABLE_NOT_WRITE,
    DISABLE_NOT_WRITE,

    MAX
};
enum class RASTERIZER_STATE {
    FILL_AND_CULL,
    FILL_AND_CULL_COUNTERCLOCK,
    FILL_NOT_CULL,
    FILL_NOT_CULL_COUNTERCLOCK,
    WIREFRAME_AND_CULL,
    WIREFRAME_AND_CULL_COUNTERCLOCK,
    WIREFRAME_NOT_CULL,
    WIREFRAME_NOT_CULL_COUNTERCLOCK,

    MAX
};
enum class BLEND_TYPE {
    NONE,
    ALPHA,
    ADD,
    SUBTRACT,
    REPLACE,
    MULTIPLY,
    LIGHTEN,
    DARKEN,
    SCREEN,

    MAX
};